# MCTS增强训练配置文件
# 专门为MCTS规划优化的配置

# 训练参数
train:
  max_episodes: 2000          # 最大训练轮数（MCTS训练较慢，减少轮数）
  max_steps: 1500            # 每轮最大步数
  batch_size: 256            # 批次大小（MCTS需要更多内存）
  warmup_steps: 10000        # 预热步数
  update_interval: 2         # 更新间隔（MCTS决策较慢，减少更新频率）
  sequence_length: 10        # 序列长度
  num_obstacles: 3           # 障碍物数量
  replay_buffer_capacity: 1000000  # 经验回放缓冲区容量
  
  # 学习率调度
  gamma: 0.99                # 折扣因子
  tau: 0.005                 # 软更新系数
  alpha: 0.2                 # 熵系数

# 网络结构
network:
  hidden_dim: 256            # 隐藏层维度（MCTS需要平衡性能和速度）
  num_layers: 3              # 网络层数
  dropout_rate: 0.1          # Dropout率
  activation: 'relu'         # 激活函数

# 优化器配置
optimizer:
  actor_lr: 1e-4             # Actor学习率
  critic_lr: 1e-4            # Critic学习率
  world_model_lr: 1e-3       # 世界模型学习率
  weight_decay: 1e-5         # 权重衰减
  gradient_clip_norm: 1.0    # 梯度裁剪

# 奖励配置
reward:
  # 基础奖励
  reach_goal_bonus: 1000.0   # 到达目标奖励
  collision_penalty: -1000.0 # 碰撞惩罚
  timeout_penalty: -100.0    # 超时惩罚
  
  # 安全奖励
  safety_distance: 20.0      # 安全距离
  safety_penalty_weight: 2.0 # 安全距离惩罚权重
  
  # 因果奖励
  causal_credit_bonus: 5.0   # 因果信誉奖励
  
  # 高级奖励权重（MCTS更注重长期规划）
  comfort_weight: 0.15       # 舒适性权重
  efficiency_weight: 0.1     # 能效权重
  safety_weight: 0.5         # 安全性权重（提高）
  goal_weight: 0.25          # 目标权重
  
  # 惩罚权重
  jerk_penalty_weight: 0.05  # Jerk惩罚权重
  energy_penalty_weight: 0.05 # 能耗惩罚权重

# 因果强化学习配置
causal:
  enable_counterfactual: true    # 启用反事实推理
  enable_intervention: true      # 启用干预推理
  world_model_update_interval: 5 # 世界模型更新间隔
  prediction_horizon: 8          # 预测时间范围（减少以配合MCTS）
  
  # 决策权重
  reward_weight: 0.8             # 奖励权重（提高）
  safety_weight: 0.2             # 安全性权重
  uncertainty_weight: 0.1        # 不确定性权重
  
  # 世界模型参数
  world_model_lr: 1e-3           # 世界模型学习率
  kl_weight: 0.1                 # KL散度权重
  uncertainty_threshold: 0.5     # 不确定性阈值

# 液态神经网络配置
lnn:
  enable_lnn: true              # 启用LNN
  liquid_neurons: 128           # 液态神经元数量（减少以配合MCTS）
  time_constant: 0.1            # 时间常数
  sequence_length: 10           # 序列长度
  gradient_clip_norm: 1.0       # 梯度裁剪

# MCTS规划配置（核心配置）
mcts:
  enable_mcts: true             # 启用MCTS规划
  num_simulations: 80           # 模拟次数（平衡性能和速度）
  exploration_constant: 1.2     # 探索常数
  gamma: 0.99                   # 折扣因子
  max_depth: 15                 # 最大搜索深度
  temperature: 1.0              # 动作选择温度
  
  # 高级MCTS特性
  enable_uncertainty_aware: true # 启用不确定性感知
  uncertainty_threshold: 0.5    # 不确定性阈值
  adaptive_simulations: true    # 自适应模拟次数
  min_simulations: 40           # 最小模拟次数
  max_simulations: 120          # 最大模拟次数
  
  # MCTS优化参数
  uct_c1: 1.414                 # UCT算法中的c1参数
  uct_c2: 1.0                   # UCT算法中的c2参数
  progressive_widening: true    # 渐进式扩展
  progressive_widening_alpha: 0.5 # 渐进式扩展参数
  
  # 性能优化
  parallel_simulations: false   # 并行模拟（需要更多内存）
  cache_predictions: true       # 缓存预测结果
  prune_threshold: 0.1          # 剪枝阈值

# 课程学习配置
curriculum:
  success_threshold: 0.8        # 成功率阈值（MCTS期望更高）
  collision_threshold: 0.05     # 碰撞率阈值（MCTS期望更低）
  performance_window: 50        # 性能窗口大小
  min_episodes_per_scenario: 10 # 每个场景最小episode数
  
  # 场景权重（MCTS更适合复杂场景）
  scenario_weights:
    straight_path: 0.5
    curved_path: 0.8
    static_obstacles: 1.0
    dynamic_obstacles: 1.2
    intersection: 1.5
    narrow_passage: 1.3
    complex_scenario: 1.8

# 安全约束配置
safety:
  max_speed: 6.0               # 最大速度 (m/s)（MCTS更保守）
  min_turn_radius: 3.5         # 最小转弯半径 (m)
  max_acceleration: 1.5        # 最大加速度 (m/s²)
  max_angular_velocity: 0.8    # 最大角速度 (rad/s)
  
  # 动作限制
  action_limits:
    min_action: -1.0           # 最小动作值
    max_action: 1.0            # 最大动作值

# 评估配置
evaluation:
  eval_interval: 50            # 评估间隔（MCTS训练较慢）
  eval_episodes: 5             # 评估episode数
  save_interval: 100           # 保存间隔
  
  # 评估指标
  metrics:
    - success_rate
    - collision_rate
    - avg_reward
    - avg_steps
    - comfort_score
    - efficiency_score
    - mcts_simulations
    - mcts_depth

# 监控配置
monitoring:
  log_interval: 5              # 日志间隔
  tensorboard: true            # 启用TensorBoard
  save_replays: false          # 保存回放
  
  # 性能阈值（MCTS期望更高）
  performance_thresholds:
    min_success_rate: 0.85     # 最小成功率
    max_collision_rate: 0.03   # 最大碰撞率
    min_avg_reward: 150.0      # 最小平均奖励

# 高级特性配置
advanced:
  # 不确定性感知
  uncertainty_aware: true      # 启用不确定性感知
  exploration_bonus: 0.3       # 探索奖励
  safety_penalty: 1.5          # 安全惩罚
  
  # 自适应训练
  adaptive_training: true      # 启用自适应训练
  lr_decay_factor: 0.95       # 学习率衰减因子
  min_lr: 1e-6                # 最小学习率
  
  # 多目标优化
  multi_objective: true        # 启用多目标优化
  pareto_weight: 0.6          # Pareto权重
  
  # MCTS特定优化
  mcts_warmup_episodes: 100    # MCTS预热episode数
  mcts_learning_rate: 0.1     # MCTS学习率
  mcts_momentum: 0.9          # MCTS动量
