# 优化的SAC训练配置文件
# 用于履带车快速路径规划与动态避障

train:
  max_episodes: 2000          # 增加训练轮数
  max_steps: 1500            # 增加每轮最大步数
  batch_size: 512            # 增大批次大小，提高训练稳定性
  save_interval: 50          # 模型保存间隔
  warmup_steps: 10000        # 增加预热步数，积累更多初始经验
  num_obstacles: 3           # 考虑的障碍物数量
  enable_slope_features: true  # 启用坡度/高程特征。true：状态中加入最近路面 height/slope 两维；false：以 [0,0] 占位
  slope_preview_meters: 0      # 坡度预瞄距离(米)。>0 时可扩展加入前方坡度统计（本次实现保留最小版，先不启用）
  max_speed_downhill_factor: 0.7 # 下坡最大速度缩放系数(0~1)。仅在下坡生效，越小表示限速越严格

network:
  hidden_dim: 512            # 增加网络宽度，提高表达能力

optimizer:
  gamma: 0.99                # 折扣因子
  tau: 0.005                 # 软更新参数
  actor_lr: 3e-4             # Actor学习率
  critic_lr: 3e-4            # Critic学习率
  replay_size: 2000000       # 增大经验池容量
  target_update_interval: 1  # 目标网络更新间隔
  lr_scheduler: "cosine"     # 学习率调度器类型
  lr_step_size: 200          # 学习率衰减步长
  lr_gamma: 0.5              # 学习率衰减因子

reward:
  # 最终状态奖励
  reach_goal_bonus: 500.0    # 到达目标奖励
  collision_penalty: -800.0  # 碰撞惩罚（增加力度）
  timeout_penalty: -100.0    # 超时惩罚
  
  # 过程奖励
  progress_weight: 2.0       # 进度奖励权重
  speed_weight: 0.1          # 速度奖励权重
  yawrate_penalty: 0.2       # 转向惩罚权重（增加，鼓励平滑转向）
  time_penalty: 0.5          # 时间惩罚权重
  
  # 坡度/高程相关奖励
  slope_uphill_weight: 0.05     # 上坡能耗惩罚权重：r -= w * max(0, slope_rad) * v
  slope_downhill_weight: 0.08   # 下坡超速惩罚权重：v > v_safe(slope) 时惩罚 (v - v_safe)
  slope_smooth_weight: 0.02     # 坡面稳定性惩罚：|yawrate|*(1+|slope|)，坡越大越鼓励平稳
  
  # 安全相关奖励
  safety_distance: 15.0      # 安全距离（米）
  safety_penalty_weight: 1.0 # 安全距离惩罚权重
  boundary_penalty_weight: 0.5 # 边界惩罚权重

# 车辆动力学参数
dynamics:
  max_speed: 5.0             # 最大速度 m/s
  a_max: 2.0                 # 最大加速度 m/s²
  b_max: 3.0                 # 最大减速度 m/s²
  track_accel_max: 2.5       # 履带最大加速度
  alpha_max: 1.0             # 最大转向角速度
  omega_abs_max: 0.8         # 最大角速度
  c_drag: 0.05               # 阻力系数
